### PR TITLE
DB Connection pooling/lifecycle fix

### LINKED ISSUE #174: OwnerId column of Event table shouldn't be nullable
Mistake when https://github.com/microsoft/azure-openai-service-proxy/commit/5ac3080a0e8060f7daba300bcb2cf12ce5f5b5d8 was done resulted in the `owner_id` column of `event` being nullable, when it shouldn't.

### PR DESCRIPTION
**Pull request by gloveboxes**
Updated db connection pool fix
Updated db models and context as generated by https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli

Fixes #174

### CODE REVIEW

File: src/AzureOpenAIProxy.Management/Database/Event.cs [hunk 1]
```diff
@@ -4,7 +4,7 @@ public partial class Event
 {
     public string EventId { get; set; } = null!;
 
-    public string OwnerId { get; set; } = null!;
+    public string? OwnerId { get; set; }
```
Comment (aaronpowell) [inline src/AzureOpenAIProxy.Management/Database/Event.cs:7]: Is owner nullable in the database? I thought it wasn't

**Review by aaronpowell — APPROVED** [review]

File: src/AzureOpenAIProxy.Management/Database/Event.cs (hunk 1 above)
Comment (gloveboxes) [reply src/AzureOpenAIProxy.Management/Database/Event.cs:7]: > Is owner nullable in the database? I thought it wasn't

Yes, it is, I think you requested that ages ago, as it made it easier for you to create the event.

The models and db context were created using the EF scaffolding tool...

dg

Comment (aaronpowell) [reply src/AzureOpenAIProxy.Management/Database/Event.cs:7]: Ah no, it's not meant to be null, https://github.com/microsoft/azure-openai-service-proxy/commit/5ac3080a0e8060f7daba300bcb2cf12ce5f5b5d8 is the change and it's a mistake when I did the column type change.

It doesn't make sense to have an event that doesn't have an owner, if we had events without owners then how would we ever access them?

I'll create a separate bug to fix that.

**Review by aaronpowell — APPROVED** [review]
